name: 'Terraform'

on: [push, pull_request]

env:
  TF_LOG: INFO
  TF_VERSION: 1.1.6
  VAR: 'userid=srikz'

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    # Set the working directory to main for the config files
    defaults:
      run:
        shell: bash
        working-directory: ./random
      
    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v2

    # Install the preferred version of Terraform CLI 
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: ${TF_VERSION}

    - name: Terraform Init
      id: init
      run: terraform get .

    - name: Terraform paln
      id: plan
      run: terraform plan -var ${VAR} -out plan.txt

    - name: Terraform Apply
      id: apply
      run: terraform apply plan.txt

 